browser = chrome
testurl = https://tulip-uat.tntra.io/tntra/login

#login credential for mentor
Emailadress = Qafox12@gmail.com
Pass = Qafox@123

#login credential for user
username = vatsal.prajapati@tntra.io
passward = Vatsal@123

###### Header ######
#plusicon menu list
automationAccelerationInn = Innovation
automationAccelerationEng = Engineering
automationAccelerationVen = Ventures

#language menu list
languageEn = English
languageJa = Japanese

####### Innovation Details ########
InnovationTitle = QA Automation
Theme = General
Domain = FinTech
ReferenceLink = https://www.google.com
Tags = Artificial Intelligence
Country = India
SelectUseCode = Music
Description = Lorem ipsum dolor sit amet, consectetur adipiscin.

username = parth.patel@tntra.io
passward = Parth@123

ForgotEmail = forgot@yopmail.com
