browser = chrome
testurl = https://tulip-uat.tntra.io/tntra

#login credential for mentor
Emailadress = Qafox12@gmail.com
Pass = Qafox@123

#login credential for user
mentorusername = vatsal.prajapati@tntra.io
mentorpassward = Vatsal@123

username = parth.patel@tntra.io
password = Parth@123

###### Header ######
#plusicon menu list
automationAccelerationInn = Innovation
automationAccelerationEng = Engineering
automationAccelerationVen = Ventures

#language menu list
languageEn = English
languageJa = Japanese

####### Automation Acceleration Details ########
Title = QA Automation
Theme = Information
Domain = tech
ReferenceLink = https://www.google.com
Tags = Artificial Intelligence
Country = India
SelectUseCode = Music
Description = Lorem ipsum dolor sit amet, consectetur adipiscin.
Source = Other
ProgramInterest = Automation
YearOfExp = 3
Referral = Referral
Tasks = Tasks
Challenges = Challenges

Priority = Medium
DiffLevel = Intermediate
Skills = Technical
ManUser = Zeel
AssigUser = Zeel
TimeZoneforTaskChallenge = canada/central

#username = parth.patel@tntra.io
#passward = Parth@123
username1 = vatsal.prajapati@tntra.io
password1 = Vatsal@123
FullName = Vatsal Prajapati
FName = Vatsal
LName = Prajapati
Comp = Tntra
VenComp = QA Automation
Phone = 9876543210

ForgotEmail = forgot@yopmail.com

StartMonth = June
StartYear = 2020
EndMonth = April
EndYear = 2024
